# Generated by Django 2.0.dev20170614170706 on 2017-06-30 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defaultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='descriptionStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='interactionStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_count', models.IntegerField(default=1)),
                ('level_option', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_text', models.CharField(max_length=200)),
                ('descStatement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandvigne.descriptionStatement')),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainField', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='levels',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandvigne.Variable'),
        ),
        migrations.AddField(
            model_name='interactionstatement',
            name='InteractionStatement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive', to='grandvigne.Vignette'),
        ),
        migrations.AddField(
            model_name='descriptionstatement',
            name='DescriptionStatement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descript', to='grandvigne.Vignette'),
        ),
    ]
