# Generated by Django 2.0.dev20170614170706 on 2017-06-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandvigne', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionstatement',
            old_name='DescriptionStatement',
            new_name='vignette',
        ),
        migrations.RenameField(
            model_name='interactionstatement',
            old_name='InteractionStatement',
            new_name='vignette',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='descStatement',
        ),
        migrations.AddField(
            model_name='levels',
            name='vignette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='grandvigne.Vignette'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='vignette',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='grandvigne.Vignette'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaultmodel',
            name='text',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='defaultmodel',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptionstatement',
            name='description_text',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='interactionstatement',
            name='interaction_text',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level_option',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_text',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='domainField',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
