# Generated by Django 2.0.dev20170614170706 on 2017-07-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandvigne', '0002_auto_20170630_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='vignette',
            name='description_text',
            field=models.CharField(default='Whose STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='vignette',
            name='interaction_text',
            field=models.CharField(default='SOME Test', max_length=200),
        ),
        migrations.AddField(
            model_name='vignette',
            name='level_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vignette',
            name='level_option',
            field=models.CharField(default='name STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='vignette',
            name='variable_text',
            field=models.CharField(default='their STRING', max_length=200),
        ),
    ]
