# Generated by Django 2.0.dev20170614170706 on 2017-07-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandvigne', '0004_auto_20170707_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionstatement',
            name='description_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='descriptionstatement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='descriptionstatement',
            name='variable_text',
        ),
        migrations.AddField(
            model_name='descriptionstatement',
            name='variable_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grandvigne.Variable'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='variable',
            name='levels',
        ),
        migrations.AddField(
            model_name='variable',
            name='levels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grandvigne.levelModel'),
        ),
        migrations.RemoveField(
            model_name='vignette',
            name='description_text',
        ),
        migrations.AddField(
            model_name='vignette',
            name='description_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grandvigne.descriptionStatement'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
